version: "3.8"
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./sample_with_data.sql:/docker-entrypoint-initdb.d/sample_with_data.sql:ro
    ports:
      - "5432:5432"  # Доступ к базе для локальной разработки

  app:
    build:
      context: ./app
    image: uvicorn-app
    ports:
      - "8090:8090"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
    depends_on:
      - postgres

  nginx:
    build:
      context: ./nginx
    image: nginx-static
    ports:
      - "8091:80"
    depends_on:
      - app

# Вынесенные переменные окружения
env_file:
  - .env
