apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracker
  labels:
    app: tracker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tracker
  template:
    metadata:
      labels:
        app: tracker
    spec:
      containers:
      - name: task-tracker
        image: 192.168.2.100:5000/task-tracker:latest
        ports:
        - containerPort: 8090
        imagePullPolicy: Always
        env:
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: tracker-config
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: tracker-config
              key: POSTGRES_PORT
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: tracker-config
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: tracker-config
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tracker-secret
              key: POSTGRES_PASSWORD
      imagePullSecrets:  # Добавлено
      - name: registry-secret
