apiVersion: v1
kind: Service
metadata:
  name: tracker-svc
  labels:
    app: tracker
spec:
  ports:
  - port: 80
    targetPort: 8090
    protocol: TCP
  selector:
    app: tracker
  type: ClusterIP
