apiVersion: v1
data:
  create-replica-user.sh: "#!/bin/bash\nset -e\n\npsql -v ON_ERROR_STOP=1 --username
    \"$POSTGRES_USER\" --dbname \"$POSTGRES_DB\" <<-EOSQL\n\tCREATE ROLE replication
    WITH REPLICATION PASSWORD '$REPLICATION_PASSWORD' LOGIN\nEOSQL\n"
  master.conf: |
    wal_level = replica
    max_wal_senders = 3
    max_replication_slots = 3
  pg_hba.conf: |
    local   all             all                                     trust
    host    all             all             127.0.0.1/32            trust
    host    all             all             ::1/128                 trust
    local   replication     all                                     trust
    host    replication     all             127.0.0.1/32            trust
    host    replication     all             ::1/128                 trust
    host    replication     replication     all                     md5
    host all all all md5
  postgres.conf: |
    listen_addresses = '*'
    max_connections = 100                   # (change requires restart)
    shared_buffers = 128MB                  # min 128kB
    dynamic_shared_memory_type = posix      # the default is the first option
    log_timezone = 'UTC'
    datestyle = 'iso, mdy'
    timezone = 'UTC'
    lc_messages = 'en_US.utf8'                      # locale for system error message
    lc_monetary = 'en_US.utf8'                      # locale for monetary formatting
    lc_numeric = 'en_US.utf8'                       # locale for number formatting
    lc_time = 'en_US.utf8'                          # locale for time formatting
    default_text_search_config = 'pg_catalog.english'
    include_if_exists = 'master.conf'
    include_if_exists = 'replica.conf'
  replica.conf: hot_standby = on
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: postgres
